version: '3'
services:
  influxdb:
    image: influxdb:2.6.1
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=myuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=mypassword
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    ports:
      - "8086:8086"
      - "8082:8082"
    volumes:
      - ./influxdb:/var/lib/influxdb

  api:
    build:
      context: .
      dockerfile: Dockerfile
      image: tracker-api:v1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
    volumes:
      - ./.env:/app/.env:ro