version: '3'
services:
  influxdb:
    image: influxdb:${INFLUXDB_VERSION}
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INIT_ADMIN_TOKEN}
    ports:
      - ${INFLUXDB_PORT}:${INFLUXDB_PORT}
    volumes:
      - ${DATA_PATH}/influxdb:/var/lib/influxdb

  api:
    image: omv.lan:5000/lan/tracker-api:${TRACKERAPI_VERSION}
    ports:
      - 8100:${API_PORT}
    depends_on:
      - influxdb
    environment:
      - URL=http://influxdb:${INFLUXDB_PORT}
      - PORT=${API_PORT}
      - TOKEN=${INIT_ADMIN_TOKEN}
      - ORG=${INIT_ORG}
      - BUCKET=${INIT_BUCKET}